### PR TITLE
Only calling onChange when I expected it to be called

### PR DESCRIPTION
**Pull request by thataustin**
Here's what I changed:
- `updateValueFromPosition` now returns the new value, and not the slider position
    - This return value wasn't being used anywhere as far as I can tell, so it should be a safe change.
- `updateValueFromPosition` no longer calls `this.props.onChange` (which was getting called way to often from my perspective as a consumer of this component)
- `handleUp` and `clickOnTrack` do now call `this.props.onChange`, which seems like a reasonable time to call that method

### CODE REVIEW

**Comment by akshat1** [comment]
@thataustin I'm sorry it took a while for us to respond to your pull-request. We are looking at it currently and we will get back to you soon. Thanks for contributing!

**Comment by thataustin** [comment]
@akshat1 - cool, I look forward to hearing feedback.  I didn't leave a great description on why I want these changes, but the crux is that I wanted this component to behave more like react-bootstrap's components - which I deem to be very easy to interact with as a developer.

I'm not entirely sure I covered every edge case, so feel free to review thoroughly.  I will say that I've been using my fork for a bit, though, and it's a pretty good experience so far.

**Comment by thataustin** [comment]
Check out how the react-color module handles a similar situation with their different onChange handlers: http://casesandberg.github.io/react-color/#api-onChangeComplete

I like how they fire the onChange on drag, but the onChangeComplete only gets fired after it's done.  That's exactly what I was looking for in this module.  What do you think about that API design?

**Comment by akshat1** [comment]
Hi @thataustin. We just published version 2.0.0 on npm, which addresses the problem you were trying to solve, while not majorly breaking the existing API. Take a look and let us know if it serves your purpose.

I don't mind the idea of a separate event for onChangeComplete, but I think one should be able to do the same thing by debouncing the onChange handler.

**Comment by thataustin** [comment]
I'm a little bit confused about what's happened so far.  I tried out he 2.0 version and it still fires on Drag.  That was really the main issue I had.  It looks like you did add a `triggerOnChangeWhileDragging` to the `slider-core` component, but that's not accessible to me because I'm only importing `slider.js` and `triggerOnChangeWhileDragging` doesn't get passed through to slider core.  

What am I missing here?  I will say that I like the idea of an `onChangeComplete` better than a `triggerOnChangeWhileDragging`, but that may just be me.  Seems like you may want to listen to both.  Imagine I want to update my components local state (maybe to give the user a preview of something else on the page) but then I only want to sync back to the server once they are done dragging.  Adding in the `triggerOnChangeWhileDragging` doesn't allow me to have access to both.

**Comment by akshat1** [comment]
@thataustin thanks for trying out 2.0. Turns out we had a bug, and the new prop `triggerOnChangeWhileDragging ` was not being sent to slider-core. Here is a PR (https://github.com/NerdWallet/nw-react-slider/pull/21) which fixes that. Would you like to check it out? The demo page now illustrates `triggerOnChangeWhileDragging` (in the PR).

We have `onDragEnd` which might serve what you want to do with `onChangeComplete`, unfortunately it is only called with position and not with value (though we might consider changing that to make it the same as onChange).

**Comment by akshat1** [comment]
Addressed by `triggerOnChangeWhileDragging` in v2.1

**Pull request closed without merging**
